### ISSUE TITLE
Support Vulkan

### ISSUE THREAD

**Issue by fire** [cadaver/turso3d#1]
Since your message on the Urho3d thread, how are your plans of supporting Vulkan in turso3d?

**Comment by cadaver** [comment]
When / if I ever get around to playing with the modern API's, it's extremely likely I'lll do it in Turso3D. But there's no firm timeline, and first I may need to do other reworking.

**Comment by fire** [comment]
Also, if I wanted to modify turso3d to support Vulkan, is that ok?

**Comment by cadaver** [comment]
The license gives you full permission to do so.

**Comment by amerkoleci** [comment]
I'm working on adding all thoose next gen features, project is here: https://github.com/amerkoleci/alimer
Still very WIP but used Turso3D as started point.

**Comment by cadaver** [comment]
Hey, nice! I think I somehow misunderstood Alimer to be based on Urho3D instead. It seems I got sidetracked by C64 development and am still not out of it :)

**Comment by amerkoleci** [comment]
At the beginning I wanted to use Urho3d but found it difficult to add Vulkan and modernize rendering, thus I decided to go with Turso3d and so far got lot of cleanup and working on Spirv intergation and graphics backend separation

**Comment by cadaver** [comment]
Codebase was now repurposed to strictly be an OpenGL 3.2+ toy renderer implementation also for old hardware. Therefore this issue will be closed.

**Comment by amerkoleci** [comment]
@cadaver Would be possible to abstract the GL stuff, I would like to add Vulkan support (in my fork in case).

I'm asking you as I saw you're calling gl directly in Renderer.cpp as well

**Comment by cadaver** [comment]
This incarnation of the codebase purposefully embraces OpenGL and its constructs to be more direct (and fun) to code against, also the inner loops call OpenGL directly where it makes sense. You can of course decide to do differently in your fork, but then it will diverge.

**Comment by amerkoleci** [comment]
I see, wouldn't make more sense to just use uniform buffers?

I'm quite sure most devices support them, even old and mobiles as well, and WebGL 2.0 (in case) is supported anywhere.

**Comment by cadaver** [comment]
There still are significant performance problems across GPU vendors with something like using an uniform buffer for an object world transform, and changing it for every call. Whereas calling glUniform performs much better.

Uniform buffers are OK for stuff you want same across shaders and across draws, for example camera matrices and light data for a forward+ renderer.

**Comment by amerkoleci** [comment]
I just setup fork here (https://github.com/amerkoleci/turso3d)

Changed some stuff in LICENSE and separated LICENSES in ThirdParty, do you find any issues with thoose changes?
