### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by 1vanK** [cadaver/turso3d#2]
I'm glad you're back to creating the new masterpiece. I added a link to Turso3D on Urho3D main page and archive repo. I wish you good luck with this project and hope that this project will not repeat the mistakes of Urho3D.

**Comment by cadaver** [comment]
Thank you! This is strictly an engine experiment for my personal use and what I feel like working with at the moment. The end goal is kind of the same which Urho3D had at the beginning, that if I ever get around to making a 3D game on PC I would use this as the engine.

**Comment by 1vanK** [comment]
By the way, have you seen this engine? http://tesseract.gg/

You might be interested in some of the possibilities

**Comment by cadaver** [comment]
Thanks for reminding! I remember looking at it way back. Turso3D already does some things similarly, like only rendering changed shadowmaps, and packing them into an atlas. The global illumination method is interesting.
