### ISSUE TITLE
Workqueue stuck on loop

### ISSUE THREAD

**Issue by AthosArantes** [cadaver/turso3d#7]
The workqueue gets stuck in it's loop waiting for pending tasks to finish.
Adding the dependency causes the pending tasks to increment, but because the rootLevelOctants is empty there's no work task to decrement it.

https://github.com/cadaver/turso3d/blob/86aa704eab1b4682c1e7c6a8bd4cede3961e2124/Turso3D/Renderer/Renderer.cpp#L338-L349

How to reproduce:
Using the supplied Turso3DTest, just put a return statement on scene creation preset 0.

As a workaround the dependency is only set if the rootLevelOctants is not empty, but I'm not sure if that's correct approach.

**Comment by cadaver** [comment]
Thanks, good find! Clients of the WorkQueue need to make sure they don't add dependencies that will not complete, so Renderer should early-out in case of no octants (nothing to render)
