### ISSUE TITLE
About execution context.

### ISSUE THREAD

**Issue by snowfoxer** [cadaver/turso3d#8]
Hi, I noticed that you dropped the execution context class in urho3d. Can you tell me why? I'm interested in this.

**Comment by cadaver** [comment]
It just simplifies the code, when classes can instead keep static information for global stuff, and subsystems can be accessed anywhere. Bear in mind, this is an experimental / toy engine. In Urho3D the idea was to theoretically allow multiple engine instances to exist in the same process with multiple contexts, but it's something that every class / feature would need to test that it actually works (also considering 3rd party libs)

**Comment by snowfoxer** [comment]
Thanks for the explanation, I also think this is a good architecture for communication between multi-subsystems. In scripting languages I see it's a mapping of a context to a vm. To keep the script simple, this is fine.
