### ISSUE TITLE
Error in an operator overload

### ISSUE THREAD

**Issue by w6rsty** [cadaver/turso3d#9]
Hi, I found an error in WeakArrayPtr.
The compiler says: subscripted value is not an array, pointer, or vector.

I haven't found any use case of this operator overload in the entire project.This leads to no instantiation of this function, so you didn't find this error.
https://github.com/cadaver/turso3d/blob/ffebacd42da3f4c1bdfcfee489de707c8bf99a12/Turso3D/Object/Ptr.h#L587-L600

This should be:
```cpp
return rawPtr[index];
```
If I misunderstood your meaning, please forgive me :)

**Comment by cadaver** [comment]
Thank you for noting!
